# Generated by Django 6.1 on 2026-08-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_remove_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, help_text='Payment gateway transaction reference ID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workspacetag',
            name='current_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tag', to='workspaces.booking'),
        ),
    ]
