# Generated by Django 6.1 on 2026-09-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_booking_reference_alter_workspacetag_current_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, help_text='Payment gateway transaction reference ID (Auto-generated on save)', max_length=100, null=True, unique=True),
        ),
    ]
