# Generated by Django 6.1 on 2026-08-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsletter_delete_enquiry_delete_galleryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('CONFERENCE_ROOM', 'Conference Room'), ('PRIVATE_SPACE', 'Private Space'), ('PODCAST', 'Podcast Studio'), ('GENERAL', 'General Enquiry')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('category', models.CharField(choices=[('HOME_CAROUSEL', 'Home Carousel'), ('WORKSPACE', 'Workspace'), ('PODCAST', 'Podcast Studio'), ('EVENTS', 'Events')], default='HOME_CAROUSEL', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers display first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
