# Generated by Django 6.1 on 2026-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_issued_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='student',
        ),
        migrations.AddField(
            model_name='certificate',
            name='student_email',
            field=models.EmailField(blank=True, help_text="Optional: Student's email for records", max_length=254, null=True),
        ),
    ]
