# Generated by Django 6.1 on 2026-09-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('LEAD_DEVELOPER', 'Lead Developer'), ('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('INSTRUCTOR', 'Instructor'), ('MARKETER', 'Marketer'), ('STAFF', 'Staff'), ('CUSTOMER', 'Customer')], default='CUSTOMER', help_text="The user's role in the PIHUB system.", max_length=20),
        ),
    ]
